### ISSUE TITLE
which functionalities will affect if we build tweetnacl without electron ?

### ISSUE THREAD

**Issue by sandipmgiri** [dchest/tweetnacl-js#146]
The electron dependency is not supported on ppc64le platform , hence I have disabled it while building tweetnacl. Just wanted to understand which functionalities are getting disabled due to electron dependency.

Thanks in advance !

**Comment by dchest** [comment]
It's only used for testing. In fact, it's a [devDependency](https://github.com/dchest/tweetnacl-js/blob/master/package.json#L44-L54), so it shouldn't be installed by default if you use `npm install`.

**Comment by sandipmgiri** [comment]
The `npm install `command itself trying to install the `electron` dependency, seems its not an optional dependency..

```
$ npm install
> electron@1.8.8 postinstall /home/test/tweetnacl-js/node_modules/electron
> node install.js

Downloading electron-v1.8.8-linux-ppc64.zip
Error: GET https://github.com/electron/electron/releases/download/v1.8.8/electron-v1.8.8-linux-ppc64.zip returned 404
/home/test/tweetnacl-js/node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron v1.8.8 for linux-ppc64 at https://github.com/electron/electron/releases/download/v1.8.8/electron-v1.8.8-linux-ppc64.zip
    at Request.<anonymous> (/home/test/tweetnacl-js/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/test/tweetnacl-js/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
tweetnacl@1.0.0 /home/test/tweetnacl-js
...

`-- xhr-write-stream@0.1.2  extraneous

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! electron@1.8.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.8.8 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/tweetnacl-js/npm-debug.log
```

**Comment by sandipmgiri** [comment]
@dchest Thanks for info.  !!
